---
title: C28105
ms.date: 11/04/2016
ms.prod: visual-studio-dev15
ms.topic: reference
f1_keywords:
- C28105
helpviewer_keywords:
- C28105
ms.assetid: 5afdec78-30eb-470c-980f-93d0cb3e74cc
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: a8dd633c6c56d18e25e3a40b00cca25a28ba3e2c
ms.sourcegitcommit: 37fb7075b0a65d2add3b137a5230767aa3266c74
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 01/02/2019
ms.locfileid: "53985836"
---
# <a name="c28105"></a>C28105
Upozornění C28105: Nevrácení prostředku z důvodu výjimky

 Zadaný prostředek není uvolněn, pokud je vyvolána výjimka. Příkaz určený argumentem cesta může vyvolat výjimku. Toto upozornění je podobný upozornění [C28103](../code-quality/c28103.md), s tím rozdílem, že v tomto případě se jedná výjimku.

## <a name="example"></a>Příklad
 Následující příklad kódu generuje toto upozornění:

```
res = KeSaveFloatingPointState(buffer);

res = AllocateResource(Resource);
char *p2 = new char[10]; // could throw

delete[] p2;
FreeResource(Resource)
```

 Následující příklad kódu se vyhnete toto upozornění:

```
res = AllocateResource(Resource);
char *p2;

try {
    p2 = new char[10];
} catch (std::bad_alloc *e) {
    // just handle the throw
    ;
}
FreeResource(Resource)
```