---
title: C28198
ms.date: 11/04/2016
ms.prod: visual-studio-dev15
ms.topic: reference
f1_keywords:
- C28198
helpviewer_keywords:
- C28198
ms.assetid: 8bad4acb-712c-43f5-81d1-45d92092d4c5
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: 83829a3178eee3deeeab9d23044c6d1d98af6468
ms.sourcegitcommit: 37fb7075b0a65d2add3b137a5230767aa3266c74
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 01/02/2019
ms.locfileid: "53954867"
---
# <a name="c28198"></a>C28198
upozornění C28198: Možná vzniká nevrácení paměti z důvodu výjimky.

 Toto upozornění signalizuje, že, který přidělenou paměť není uvolnění poté, co je vyvolána výjimka. Příkaz na konci cesty může vyvolat výjimku. Paměť byla předána funkci, která může uložit kopii být později uvolněna.

 Toto upozornění je velmi podobná upozornění [C28197](../code-quality/c28197.md). Poznámky, které se doporučují pro použití s upozorněním [C28197](../code-quality/c28197.md) je také možné použít.

## <a name="example"></a>Příklad
 Následující příklad kódu generuje toto upozornění:

```
char *p1 = new char[10];
char *p2 = new char[10];

test(p1);   // does not save a copy of p

delete[] p2;
delete[] p1;
```

 Následující příklad kódu se vyhnete toto upozornění:

```
char *p1 = new char[10];
char *p2 = NULL;

test(p1);   // does not save a copy of p
try {
    p2 = new char[10];
} catch (std::bad_alloc *e) {
    // just handle the throw
    ;
}
```