---
title: C28105
ms.date: 11/04/2016
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C28105
helpviewer_keywords:
- C28105
ms.assetid: 5afdec78-30eb-470c-980f-93d0cb3e74cc
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: 455e06476d6841f468a64d45b350e45f3e8d1a75
ms.sourcegitcommit: 42ea834b446ac65c679fa1043f853bea5f1c9c95
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 04/19/2018
---
# <a name="c28105"></a>C28105
Upozornění C28105: Úniku prostředků kvůli výjimce

 Zadaný prostředek není uvolněno, když dojde k výjimce. Příkaz určený argumentem cesta může vyvolat výjimku. Toto upozornění je podobná upozornění [C28103](../code-quality/c28103.md)kromě toho, že v tomto případě je zahrnuta výjimku.

## <a name="example"></a>Příklad
 Následující příklad kódu generuje toto upozornění:

```
res = KeSaveFloatingPointState(buffer);

res = AllocateResource(Resource);
char *p2 = new char[10]; // could throw

delete[] p2;
FreeResource(Resource)
```

 Následující příklad kódu zabraňuje toto upozornění:

```
res = AllocateResource(Resource);
char *p2;

try {
    p2 = new char[10];
} catch (std::bad_alloc *e) {
    // just handle the throw
    ;
}
FreeResource(Resource)
```